export const PACKET_LENGTH = 4;
export const MESSAGE_TYPE = 2;
export const VERSION_LENGTH = 1;
export const SEQUENCE_LENGTH = 4;
export const PAYLOAD_LENGTH = 4;
export const TOTAL_LENGTH = 20;

export const MessageType = {
  TEST_MESSAGE_TO_CLIENT: 9990,
  TEST_MESSAGE_TO_SERVER: 9991,

  ICYROAD_GAME_JOIN_REQUEST: 1000,

  ICYROAD_GAME_JOIN: 100,
  ICYROAD_GAME_PLAYER_SPAWN: 101,
  ICYROAD_GAME_START: 102,
  ICYROAD_GAME_PLAYER_MOVE: 103,
  ICYROAD_GAME_SYNC_NOTIFICATION: 104,
  ICYROAD_GAME_DEFEAT_NOTIFICATION: 105,
};
